[mpd] Fix option overwriting custom config
Poeschl/Hassio-Addons pull request #218
Opened 2021-03-26 17:57 UTC by LiJu09

Fix #217

2021-03-26 23:22 UTC, Poeschl reviewed
I would suggest to the leave the two new fields mandatory and just ignore any config modification when a custom configuration is used.

2021-03-27 08:58 UTC, LiJu09 commented
These two new options are already ignored because the custom configuration is copied last, so it will overwrite them.

2021-03-27 09:03 UTC, LiJu09 commented
now its better

2021-03-27 09:11 UTC, LiJu09 commented
And should not be [these lines](https://github.com/Poeschl/Hassio-Addons/blob/147ac0cab57e3e26044a6515642efa707aaa82d3/mpd/root/etc/cont-init.d/setup-settings#L6-L23) also moved to the new else or after copying custom config, because they are overwriten when custom config is copied?

2021-03-27 09:14 UTC, Poeschl commented
It makes 100% sense that the also go in the "not custom" part of the if. Please move them as well

2021-03-27 09:16 UTC, LiJu09 commented
then it shoud be also mentioned in docs

2021-03-27 09:35 UTC, LiJu09 commented
Also fix typo in docs, and added examples for all options. Is it all right?

2021-03-27 09:36 UTC, Poeschl commented
Can the docs show the mandatory config at the top, thats what the shown yaml with the normalization was intended.
Also shouldn't the path matchers stay in the addon config?

2021-03-27 09:43 UTC, LiJu09 commented
Is this order of options better?

2021-03-27 09:51 UTC, Poeschl requested changes
When the docs are update again (sry for my nitpicking) and the path matchers are back for `media_folder` and `playlist_folder` the PR can be merged.

2021-03-27 09:51 UTC, Poeschl commented on mpd/DOCS.md
> +If a custom configuration is specified, all other options are ignored.
Can that notice go to the custom configuration section? Maybe as highlighted in bold.

2021-03-27 09:51 UTC, Poeschl commented on mpd/config.json
> +    "media_folder": "str",
I didn't meant the ordering ;) It will be automatically sorted by Home Assistant

I was wondering where the `match(/share/.+|/media/.+)` checks went.

2021-03-27 10:07 UTC, LiJu09 commented on mpd/config.json
> +    "media_folder": "str",
But check this #217 
> I have a media folder set up under a samba share which I have added to the mpd.conf by replacing the default folder to "smb://user:password@ip/folder path"

2021-03-27 10:56 UTC, LiJu09 commented on mpd/config.json
> +    "media_folder": "str",
media can be also stored on NFS or SMB server, so there can't be only `/media` and `/share`,
so maybe someting like this `match(/share/.+|/media/.+|(smb|nfs)://.+)`

2021-03-27 11:01 UTC, Poeschl commented on mpd/config.json
> +    "media_folder": "str",
Ah, thats right. I like the appended network storage check. :)

2021-03-27 11:16 UTC, Poeschl approved these changes

2021-03-27 11:17 UTC, Poeschl commented
If there are no more changes from your side, I will merge the PR. @LiJu09

2021-03-27 11:18 UTC, LiJu09 commented
Shoudn't it increase to version 1.6.0?

2021-03-27 11:20 UTC, Poeschl commented
Since there are chances how the custom_config behave. That is good idea.

2021-03-27 11:45 UTC, merged